apiVersion: v1
kind: Pod
metadata:
  name: log-writer-pod
spec:
  containers:
  - name: log-writer
    image: busybox
    command: ["/bin/sh", "-c", "while true; do date >> /data/app.log; sleep 5; done"]
    volumeMounts:
    - name: app-logs
      mountPath: /data
  volumes:
  - name: app-logs
    persistentVolumeClaim:
      claimName: app-logs-pvc
