---
- name: Secure MySQL Setup with Ansible Vault
  hosts: mohamed-vm-node
  become: yes
  vars_files:
    - vault.yml   # Encrypted file containing db_user and db_pass

  tasks:

    - name: Install MySQL server
      ansible.builtin.yum:
        name: mysql-server
        state: present
      register: mysql_install
    - debug:
        msg: "✅ MySQL installation completed successfully"
      when: mysql_install.changed

    - name: Start and enable MySQL service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
      register: mysql_service
    - debug:
        msg: "✅ MySQL service started and enabled"

    - name: Install MySQL Python library (for Ansible modules)
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present
      register: pymysql_install
    - debug:
        msg: "✅ PyMySQL library installed successfully"

    - name: Create iVolve database
      community.mysql.mysql_db:
        name: iVolve
        state: present
      register: db_creation
    - name: Verify iVolve DB creation
      ansible.builtin.debug:
        msg: "✅ Database 'iVolve' creation status: {{ 'Created' if db_creation.changed else 'Already exists' }}"

    - name: Create user with privileges on iVolve DB
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: "iVolve.*:ALL"
        host: "%"
        state: present
      register: user_creation
    - name: Verify user creation
      ansible.builtin.debug:
        msg: "✅ User '{{ db_user }}' creation status: {{ 'Created' if user_creation.changed else 'Already exists' }}"

    - name: Validate connection with created user
      ansible.builtin.shell: |
        mysql -u {{ db_user }} -p"{{ db_pass }}" -e "SHOW DATABASES;"
      register: db_output
      ignore_errors: yes

    - name: Print validation result
      ansible.builtin.debug:
        msg: >-
          {{ '✅ Database connection successful. Databases:\n' + db_output.stdout
             if db_output.rc == 0
             else '❌ Failed to connect to MySQL using provided credentials.' }}

